services:
    oai-cu:
        image: jamsier/oai-gnb:CRW25
        container_name: rfsim5g-oai-cu
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        environment: 
            USE_ADDITIONAL_OPTIONS: --rfsimulator.options chanmod
                                    --telnetsrv --telnetsrv.listenaddr 192.168.70.150
                                    --telnetsrv.shrmod ci
            ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.150
        volumes:
            - ./ran-conf/rfsim.cu.conf:/opt/oai-gnb/etc/gnb.conf
            - ../../pcap_new/:/opt/oai-gnb/etc/pcap/
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-du:
        image: jamsier/oai-gnb:CRW25
        container_name: rfsim5g-oai-du
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim
                                    --telnetsrv --telnetsrv.listenaddr 192.168.70.171
                                    --telnetsrv.shrmod ci
            ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=0s
        depends_on:
            - oai-cu
        networks:
            public_net:
                ipv4_address: 192.168.70.171
        volumes:
            - ./ran-conf/rfsim.du.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue:
        image: jamsier/oai-nr-ue:CRW25
        container_name: rfsim5g-oai-nr-ue
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -C 3619200000 -r 106 --numerology 1 --rfsimulator.serveraddr 192.168.70.171
            ASAN_OPTIONS: detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.181
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - ./ran-conf/nrue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ./lowRateDoS:/opt/oai-nr-ue/etc/lowRateDoS
            - ./normalUser:/opt/oai-nr-ue/etc/normalUser
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue2:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue2
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -C 3619200000 -r 106 --numerology 1 --rfsimulator.serveraddr 192.168.70.171 --uicc0.imsi 001010000000002
            ASAN_OPTIONS: detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.182
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - ./ran-conf/nrue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ./lowRateDoS:/opt/oai-nr-ue/etc/lowRateDoS
            - ./normalUser:/opt/oai-nr-ue/etc/normalUser
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue3:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue3
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -C 3619200000 -r 106 --numerology 1 --rfsimulator.serveraddr 192.168.70.171 --uicc0.imsi 001010000000003
            ASAN_OPTIONS: detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.183
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ./ran-conf/nrue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ./lowRateDoS:/opt/oai-nr-ue/etc/lowRateDoS
            - ./normalUser:/opt/oai-nr-ue/etc/normalUser
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue4:
        image: oai-nr-ue:latest
        container_name: rfsim5g-oai-nr-ue4
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -C 3619200000 -r 106 --numerology 1 --rfsimulator.serveraddr 192.168.70.171 --uicc0.imsi 001010000000004
            ASAN_OPTIONS: detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.184
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ./ran-conf/nrue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ./lowRateDoS:/opt/oai-nr-ue/etc/lowRateDoS
            - ./normalUser:/opt/oai-nr-ue/etc/normalUser
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        external: true
        name: oai-cn5g-public-net
